/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as MapRouteImport } from './routes/map'
import { Route as ReportRouteImport } from './routes/report'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAiRouteImport } from './routes/admin.ai'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminHistoryRouteImport } from './routes/admin.history'
import { Route as AdminImpactRouteImport } from './routes/admin.impact'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminQueueRouteImport } from './routes/admin.queue'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminTrucksRouteImport } from './routes/admin.trucks'
import { Route as AdminBinsIndexRouteImport } from './routes/admin.bins.index'
import { Route as AdminBinsBinIdRouteImport } from './routes/admin.bins.$binId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpactRoute = AdminImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrucksRoute = AdminTrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBinsIndexRoute = AdminBinsIndexRouteImport.update({
  id: '/bins/',
  path: '/bins/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBinsBinIdRoute = AdminBinsBinIdRouteImport.update({
  id: '/bins/$binId',
  path: '/bins/$binId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/worker': typeof WorkerRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bins/$binId': typeof AdminBinsBinIdRoute
  '/admin/bins/': typeof AdminBinsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/worker': typeof WorkerRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/admin': typeof AdminIndexRoute
  '/admin/bins/$binId': typeof AdminBinsBinIdRoute
  '/admin/bins': typeof AdminBinsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/map': typeof MapRoute
  '/report': typeof ReportRoute
  '/worker': typeof WorkerRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/impact': typeof AdminImpactRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/queue': typeof AdminQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/trucks': typeof AdminTrucksRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/bins/$binId': typeof AdminBinsBinIdRoute
  '/admin/bins/': typeof AdminBinsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/map'
    | '/report'
    | '/worker'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/history'
    | '/admin/impact'
    | '/admin/map'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/trucks'
    | '/admin/'
    | '/admin/bins/$binId'
    | '/admin/bins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/map'
    | '/report'
    | '/worker'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/history'
    | '/admin/impact'
    | '/admin/map'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/trucks'
    | '/admin'
    | '/admin/bins/$binId'
    | '/admin/bins'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/map'
    | '/report'
    | '/worker'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/history'
    | '/admin/impact'
    | '/admin/map'
    | '/admin/queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/trucks'
    | '/admin/'
    | '/admin/bins/$binId'
    | '/admin/bins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  MapRoute: typeof MapRoute
  ReportRoute: typeof ReportRoute
  WorkerRoute: typeof WorkerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impact': {
      id: '/admin/impact'
      path: '/impact'
      fullPath: '/admin/impact'
      preLoaderRoute: typeof AdminImpactRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trucks': {
      id: '/admin/trucks'
      path: '/trucks'
      fullPath: '/admin/trucks'
      preLoaderRoute: typeof AdminTrucksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bins/': {
      id: '/admin/bins/'
      path: '/bins'
      fullPath: '/admin/bins/'
      preLoaderRoute: typeof AdminBinsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bins/$binId': {
      id: '/admin/bins/$binId'
      path: '/bins/$binId'
      fullPath: '/admin/bins/$binId'
      preLoaderRoute: typeof AdminBinsBinIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminImpactRoute: typeof AdminImpactRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTrucksRoute: typeof AdminTrucksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminBinsBinIdRoute: typeof AdminBinsBinIdRoute
  AdminBinsIndexRoute: typeof AdminBinsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminImpactRoute: AdminImpactRoute,
  AdminMapRoute: AdminMapRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTrucksRoute: AdminTrucksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminBinsBinIdRoute: AdminBinsBinIdRoute,
  AdminBinsIndexRoute: AdminBinsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  MapRoute: MapRoute,
  ReportRoute: ReportRoute,
  WorkerRoute: WorkerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
